export enum TodosActions {
  ADD_TODO_ITEM = 'ADD_TODO_ITEM',
  REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM',
  TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS',
  EDIT_TODO_TITLE = 'EDIT_TODO_TITLE',
  REMOVE_TODO_LIST = 'REMOVE_TODO_LIST',
}
