export enum TodosActions {
  GET_TODO_LIST = 'GET_TODO_LIST',
  SET_TODO_LIST = 'SET_TODO_LIST',
  ADD_TODO_ITEM = 'ADD_TODO_ITEM',
  REMOVE_TODO_ITEM = 'REMOVE_TODO_ITEM',
  TOGGLE_TODO_STATUS = 'TOGGLE_TODO_STATUS',
  EDIT_TODO_TITLE = 'EDIT_TODO_TITLE',
  REMOVE_TODO_LIST = 'REMOVE_TODO_LIST',
  SET_LOADING_TODOS = 'SET_LOADING_TODOS'
}

export const API_BREAKPOINT = 'https://jsonplaceholder.typicode.com/todos';
